.\" Manpage for Slack JSON Parser
.TH slackjp 1 "2021 January 07" "0.2.6" "slackjp man page"


.SH NAME
slackjp \- Slack JSON Parser for Linux

.SH SYNOPSIS
slackjp 
[\fB \-h \fR] 
[\fB \-R \fR]
[\fB \-D \fI FILETYPE \fR[\fB FILETYPE...\fR]]
[\fB \-o \fI OUTPUT \fR]
[\fB \-\-version \fR]
\fB\fIdirectory\fR

.SH DESCRIPTION
Single (soon multi-) function JSON parser for Slack Workspace exports.
.SH OPTIONS
.TP
.B \-h , \-\-help
Opens the help/usage command menu.  Program exits after this function.
.TP
.B \-R, \-\-recurse
Tells SlackJP to recursively examine a folder and subfolders.  Necessary for inputs that
are not a file.
.TP
.B \-D\fI FILETYPE [FILETYPE...]
Operates like \fB\-d\fR; however, a specified file type must be provided.  The given type
will be the only file type downloaded.
.TP
.B \-o\fI OUTPUT
Sets the output location for downloaded files or other operations.  If not specified, the
current directory (./) will be used.
.TP
.B \-\-version
Prints the version number of the exectuable.  Program exits after this function.
.TP
.B directory
Sets the input location.  This should be the root directory of a Slack Workspace export.

.SH EXIT STATUS
.SS 0
Program exited appropriately and all tasks finished succesfully.
.SS 100-Series
This exclusively deals with file downloading.  All files unable to be downloaded will be
listed in an error log (err.log) alongside the return code.
.TP
.B 101
Not all files were downloaded due to broken links.
.TP
.B 102
Not all files were downloaded due to invalid file permissions.
.TP
.B 103
Not all files were downloaded due to lack of hard drive space.

.SH AUTHOR
Written by Brandt Damman (brandt.damman@spudwilson.us)